---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_paths: 
    - "**/step_definitions/"
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_paths: 
    - "**/step_definitions/"
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.sh"
