source 'https://rubygems.org'

gem 'activesupport'
gem 'cucumber', '= 2.99'
gem 'deep_struct'
gem 'mail'
gem 'nokogiri'
gem 'page-object'
gem 'parallel_tests'
gem 'rake'
gem 'report_builder'
gem 'rest-client'
gem 'retriable'
gem 'rspec'
gem 'rubocop'
gem 'watir'
gem 'watir-scroll'
gem 'yard'
gem 'yard-cucumber'
