source 'https://rubygems.org'

gem 'cucumber'
gem 'deep_struct'
gem 'mail'
gem 'nokogiri'
gem 'page-object'
gem 'parallel_tests'
gem 'rake'
gem 'report_builder'
gem 'rest-client'
gem 'retriable'
gem 'rspec'
gem 'rubocop'
gem 'watir'
